<?php

namespace Container9LcGFtO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckAttendanceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1_0iiG0.App\Entity\CheckAttendance' shared service.
     *
     * @return \App\Entity\CheckAttendance
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.1_0iiG0": it references class "App\\Entity\\CheckAttendance" but no such service exists.');
    }
}
