<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTAxulDk\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTAxulDk/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTAxulDk.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTAxulDk\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerTAxulDk\App_KernelProdContainer([
    'container.build_hash' => 'TAxulDk',
    'container.build_id' => 'b4cbb33e',
    'container.build_time' => 1664590976,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTAxulDk');
