<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_check_attendance_index' => [[], ['_controller' => 'App\\Controller\\CheckAttendanceController::index'], [], [['text', '/check/attendance/']], [], [], []],
    'app_check_attendance_new' => [[], ['_controller' => 'App\\Controller\\CheckAttendanceController::new'], [], [['text', '/check/attendance/new']], [], [], []],
    'app_check_attendance_show' => [['id'], ['_controller' => 'App\\Controller\\CheckAttendanceController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/check/attendance']], [], [], []],
    'app_check_attendance_edit' => [['id'], ['_controller' => 'App\\Controller\\CheckAttendanceController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/check/attendance']], [], [], []],
    'app_check_attendance_delete' => [['id'], ['_controller' => 'App\\Controller\\CheckAttendanceController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/check/attendance']], [], [], []],
    'app_product_index' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/product/']], [], [], []],
    'app_product_new' => [[], ['_controller' => 'App\\Controller\\ProductController::new'], [], [['text', '/product/new']], [], [], []],
    'app_product_show' => [['id'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], [], []],
    'app_product_edit' => [['id'], ['_controller' => 'App\\Controller\\ProductController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], [], []],
    'app_product_delete' => [['id'], ['_controller' => 'App\\Controller\\ProductController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], [], []],
    'app_student_index' => [[], ['_controller' => 'App\\Controller\\StudentController::index'], [], [['text', '/student/']], [], [], []],
    'app_student_new' => [[], ['_controller' => 'App\\Controller\\StudentController::new'], [], [['text', '/student/new']], [], [], []],
    'app_student_show' => [['id'], ['_controller' => 'App\\Controller\\StudentController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/student']], [], [], []],
    'app_student_edit' => [['id'], ['_controller' => 'App\\Controller\\StudentController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/student']], [], [], []],
    'app_student_delete' => [['id'], ['_controller' => 'App\\Controller\\StudentController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/student']], [], [], []],
    'app_lucky_number' => [[], ['_controller' => 'App\\Controller\\LuckyController::number'], [], [['text', '/lucky']], [], [], []],
    'app_lucky_getdate' => [[], ['_controller' => 'App\\Controller\\LuckyController::getdate'], [], [['text', '/lucky/getdate']], [], [], []],
    'app_lucky_hello' => [[], ['_controller' => 'App\\Controller\\LuckyController::welcome'], [], [['text', '/lucky/welcome']], [], [], []],
];
