<?php

namespace ContainerOpy4NC4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MdkrM0pService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MdkrM0p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MdkrM0p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'checkAttendanceRepository' => ['privates', 'App\\Repository\\CheckAttendanceRepository', 'getCheckAttendanceRepositoryService', true],
        ], [
            'checkAttendanceRepository' => 'App\\Repository\\CheckAttendanceRepository',
        ]);
    }
}
