<?php

namespace ContainerOpy4NC4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ho8CQljService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ho8CQlj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ho8CQlj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'student' => ['privates', '.errored..service_locator.ho8CQlj.App\\Entity\\Student', NULL, 'Cannot autowire service ".service_locator.ho8CQlj": it references class "App\\Entity\\Student" but no such service exists.'],
            'studentRepository' => ['privates', 'App\\Repository\\StudentRepository', 'getStudentRepositoryService', true],
        ], [
            'student' => 'App\\Entity\\Student',
            'studentRepository' => 'App\\Repository\\StudentRepository',
        ]);
    }
}
