<?php

namespace ContainerTAxulDk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QLgPRBqService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.QLgPRBq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QLgPRBq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'studentRepository' => ['privates', 'App\\Repository\\StudentRepository', 'getStudentRepositoryService', true],
        ], [
            'studentRepository' => 'App\\Repository\\StudentRepository',
        ]);
    }
}
