<?php

namespace ContainerTAxulDk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStudentService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.ho8CQlj.App\Entity\Student' shared service.
     *
     * @return \App\Entity\Student
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ho8CQlj": it references class "App\\Entity\\Student" but no such service exists.');
    }
}
