<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3evxzqu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3evxzqu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3evxzqu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3evxzqu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3evxzqu\App_KernelDevDebugContainer([
    'container.build_hash' => '3evxzqu',
    'container.build_id' => 'aa90868a',
    'container.build_time' => 1663901793,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3evxzqu');
