<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF7CtvUM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF7CtvUM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF7CtvUM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF7CtvUM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF7CtvUM\App_KernelDevDebugContainer([
    'container.build_hash' => 'F7CtvUM',
    'container.build_id' => 'b74ee98d',
    'container.build_time' => 1664602354,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF7CtvUM');
